/**
 * Block-name → block-type mapping.
 * Shared between the server (seedAstParser, seedWriter) and the client (BlockSettingsPopover).
 * Source of truth: originally extracted from the ClientSafe DB seed + migrations.
 */
export const BLOCK_TYPE_MAP: Record<string, string> = {
	accessForRequester: "general",
	activateCaroQuestionnaireOrBodyWeightMeasurement: "general",
	assignAnyActivityPerformer: "general",
	assignToActivityPerformer: "general",
	assignToHomeHolterOrganization: "general",
	assignToPreviousActiveActivityPerformer: "general",
	assignToPreviousActivityPerformer: "general",
	assignToProcessActorOrganization: "general",
	assignToRequester: "general",
	authorizeAnyOrganizationWithServiceActivityAuthorizations: "general",
	bariPostSendZorgmail: "general",
	bariPreSendZorgmail: "general",
	bariatricsNotifyProcessActor: "general",
	canPerformActivity: "choice",
	cancelProcess: "action",
	checkBooleanInActivity: "general",
	checkCaroInactivityNextStep: "general",
	checkCaroPatientCreated: "general",
	checkConditions: "general",
	checkEveryStepHasStatus: "general",
	checkForTruthy: "general",
	checkIsTheRequesterTheGp: "general",
	checkNotEmpty: "general",
	checkSomeConditions: "general",
	checkSomeStepsHaveStatus: "general",
	checkStringValueInActivity: "general",
	closeProcess: "general",
	completeProcess: "action",
	createCaroPatient: "general",
	createCompletedActivity: "general",
	createCompletedResendQuestionnaires: "general",
	createEvidencioPatient: "general",
	createExternalReferralLetter: "general",
	createMraReferralLetter: "general",
	CreateOsasNoTreatmentTaskBlock: "general",
	createOsasTaskForChosenTreatment: "general",
	createPatientTask: "general",
	createReferralLetter: "general",
	createTaskForAdminStatus: "general",
	createTherapielandRequest: "general",
	dummyAction: "action",
	dummyStep: "general",
	emailEvidencioQuestionnaireToPatient: "general",
	emailExaminationToPerformer: "general",
	fixedIntervalScheduler: "scheduled",
	hearingLossCreateRecipeLetter: "general",
	insertInGroupMeetingPatientsTable: "general",
	insertInPatientConsentsTable: "general",
	insertInProcessActorsTable: "general",
	insertPoliclinicOrganizationInProcessActorsTable: "general",
	intervalBasedOnServiceActivityScheduler: "scheduled",
	intervalWeeksBasedOnServiceActivityScheduler: "scheduled",
	invitePatientToBrightPlan: "general",
	manualStart: "start",
	osasCreateExternalReferralLetter: "general",
	osasDeleteCloudpatExaminationResults: "action",
	pauseProcess: "general",
	percentageYesOrNo: "general",
	performActivity: "activity",
	receiveEvidencioQuestionnaireStatus: "activity",
	receiveGradingResult: "general",
	receivePrickTestMeasurements: "general",
	registerCloudPatPatient: "general",
	reminderEmailEvidencioQuestionnaireToPatient: "general",
	reminderEmailToPerformer: "general",
	resumeProcess: "general",
	saveCaroFollowUpBodyWeightMeasurements: "general",
	saveCaroQuestionnaireResponse: "activity",
	saveEvidencioQuestionnaireResponse: "activity",
	saveProcessQuestionnaireResponse: "activity",
	saveResponseBody: "activity",
	sendEmailToGeneralPractitioner: "general",
	sendEmailToPatient: "general",
	sendEmailToRequester: "general",
	sendEmailToTaskPerformer: "general",
	sendEmailToTaskPerformerBasedOnNotificationSettings: "general",
	sendExaminationRecorderEmail: "general",
	sendZorgMail: "general",
	sendZorgmailToGeneralPractitioner: "general",
	sendEmailToRequesterBasedOnNotificationSettings: "general",
	sendZorgmailToRequester: "general",
	setProcessStatusFlags: "general",
	setRequesterFromCareProvider: "general",
	setRequesterFromStarter: "general",
	startProcessFromExistingProcess: "general",
	updateCaroPatientFromActivityData: "general",
	updateCaroPatientFromStep: "general",
	updateGroupMeetingPatient: "general",
	updatePatientFromActivityData: "general",
	updatePatientGeneralPractitionerFromStarter: "general",
	upsertInPatientGeneralPractitionersTable: "general",
	userChoice: "choice",
	waitForAll: "general",
};

/** Sorted list of all valid block names, for use in dropdowns. */
export const BLOCK_NAMES: string[] = Object.keys(BLOCK_TYPE_MAP).sort();
